version: '3.4'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 12345678
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - /tmp/postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
