export type Tag = {
  _id: string
  label:
    | 'Beginner'
    | 'Intermediate'
    | 'Advanced'
    | 'Breakfast'
    | 'Lunch'
    | 'Dinner'
    | 'Snacks'
    | 'Dessert'
    | 'One-Pot'
    | 'Spicy'
    | 'Summer'
    | 'Fall'
    | 'Winter'
    | 'Spring'
    | 'Comfort Food'
    | 'Healthy'
    | 'Party'
    | 'Holiday'
    | 'Quick and Easy'
    | 'Vegeterian'
    | 'Vegan'
    | 'Gluten-Free'
    | 'Grilled'
    | 'Baked'
    | 'Fried'
    | 'Steamed'
    | 'Slow Cooked'
    | 'Asian'
    | 'Italian'
    | 'Mexican'
}
